### ISSUE TITLE
Button responces cannot be captured

### ISSUE THREAD

**Issue by pjsurve15** [codeforequity-at/botium-connector-cognigy#2]
We have connected botium to test chatbot on the Cognigy platform. However, it is only working for text responses. For responses with buttons the test always fails due to timeout.

**Comment by pjsurve15** [comment]
The issue is in botium-connector-cognigy-cjs.js file. Cognigy sends response in data._data._cognigy._default instead of data._cogngiy._facebook. Due to this Quick responses with buttons and cards are not getting captured. I implement a local code fix just to make it work. Please find the changes I have made below:
![image](https://user-images.githubusercontent.com/88492134/129759693-94d89f16-36df-4a1a-8047-633702a4369e.png)
![image](https://user-images.githubusercontent.com/88492134/129759809-8dcbd1e1-f41f-4957-9401-dc2db2ca63e0.png)
Still, it is not the perfect solution. Can you please update the code accordingly?

**Comment by ujja** [comment]
Fixed, will be there with the new release.
